"""Add rating to Book

Revision ID: d4cabc0900a2
Revises: 
Create Date: 2026-02-27 14:07:22.590149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cabc0900a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('date_of_death',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('date_of_death',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
